# Generated by Django 4.0.6 on 2022-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('japanese_name', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('episodes', models.IntegerField()),
                ('season', models.CharField(choices=[('watching', 'WATCHING'), ('plan_to_watch', 'PLAN TO WATCH'), ('completed', 'COMPLETED')], default='plan_to_watch', max_length=15)),
            ],
        ),
    ]
