# Generated by Django 4.0.6 on 2022-07-09 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('japanese_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('episodes', models.IntegerField()),
                ('status', models.CharField(choices=[('watching', 'WATCHING'), ('plan_to_watch', 'PLAN TO WATCH'), ('completed', 'COMPLETED')], default='plan_to_watch', max_length=15)),
            ],
        ),
    ]
