# Generated by Django 4.0.6 on 2022-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
