# Generated by Django 4.0.6 on 2022-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='season',
        ),
        migrations.AddField(
            model_name='anime',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('watching', 'WATCHING'), ('plan_to_watch', 'PLAN TO WATCH'), ('completed', 'COMPLETED')], default='plan_to_watch', max_length=15),
        ),
        migrations.AlterField(
            model_name='anime',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='start_date',
            field=models.DateField(),
        ),
    ]
